SELECT * FROM KH_MEMBER;

--특정 테이블 내 제약조건 이름, 타입 조회
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME='KH_MEMBER';
SELECT * FROM USER_CONS_COLUMNS WHERE TABLE_NAME='KH_MEMBER';
SELECT * FROM USER_CONS_COLUMNS WHERE CONSTRAINT_NAME='SYS_C007058';

--제약조건 추가(ADD CONSTRAINT)
ALTER TABLE KH_MEMBER ADD CONSTRAINT MEM_PASS_UNQ UNIQUE(U_PASS);
--두 개의 컬럼 함께 제약조건을 추가
ALTER TABLE KH_MEMBER ADD CONSTRAINT MEM_PASS_NAME_UNQ UNIQUE(U_PASS,NAME);
--MODIFY를 이용해서도 제약조건 추가 가능
ALTER TABLE KH_MEMBER MODIFY U_ID VARCHAR2(20) PRIMARY KEY;
    --U_ID에 UNIQUE 제약조건이 이미 적용되어 있는 상태라서 오류 발생

--제약조건 삭제(DROP CONSTRAINT)
ALTER TABLE KH_MEMBER DROP CONSTRAINT MEM_PASS_UNQ;
ALTER TABLE KH_MEMBER DROP CONSTRAINT MEM_PASS_NAME_UNQ;
DESC KH_MEMBER;
    --U_ID 컬럼에 UNIQUE 제약조건 삭제
ALTER TABLE KH_MEMBER DROP CONSTRAINT SYS_C007057;
--MODIFY를 이용해서도 제약조건 추가 가능
    --U_ID 컬럼에 다시 PRIMARY KEY 설정 시 정상 적용
ALTER TABLE KH_MEMBER MODIFY U_ID VARCHAR(20) PRIMARY KEY;
--만약 PRIMARY KEY 설정이 안되는 경우(NULL 오류 발생시)
SELECT * FROM KH_MEMBER;    --U_ID 컬럼 데이터 중 NULL 데이터가 있는지 확인
--NULL 데이터가 있으면 다른 데이터로 변경하거나, 삭제 후 PRIMARY KEY 지정 가능
DELETE FROM KH_MEMBER WHERE NAME='최길동'; --NAME이 최길동인 데이터 삭제
DELETE FROM KH_MEMBER WHERE U_ID IS NULL; --U_ID가 NULL인 데이터 삭제
/*  초기에 NAME을 CHAR(15)로 지정하고 생성한 뒤 NAME의 데이터를 VARCHAR2로 수정하였기때문에 
    처음 CHAR을 설정한 크기만큼의 공백이 뒤에 생겨 공백까지 적어 삭제해주어야 함
    이름 3글자(9바이트) 공백 6칸(6바이트)*/
DELETE FROM KH_MEMBER WHERE NAME = '홍길동      ';

--제약조건 이름 변경(RENAME CONSRTRAINT)
ALTER TABLE KH_MEMBER RENAME CONSTRAINT SYS_C007061 TO MEM_ID_PRI;
ALTER TABLE KH_MEMBER RENAME CONSTRAINT SYS_C007058 TO MEM_NAME_NN;

--테이블 생성시 제약조건 이름 명시 : 컬럼 레벨 설정
CREATE TABLE CONST_NAME(
    U_NO NUMBER CONSTRAINT PK_U_NO PRIMARY KEY,
    U_ID VARCHAR2(30) CONSTRAINT UK_U_ID UNIQUE,
    U_PW VARCHAR2(50) CONSTRAINT NN_U_PW NOT NULL
);
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME='CONST_NAME';
--테이블 생성 시 제약조건 이름 명시 : 테이블 레벨 설정
--제약조건 이름은 테이블이 달라도 같은 이름을 사용할 수 없음
CREATE TABLE CONST_NAME2(
    U_NO NUMBER,
    U_ID VARCHAR(30),
    U_PW VARCHAR(50) CONSTRAINT NN_U_PW2 NOT NULL,
    CONSTRAINT PK_U_NO2 PRIMARY KEY(U_NO),
    CONSTRAINT UK_U_ID2 UNIQUE(U_ID)
);
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME='CONST_NAME2';

--테이블 이름 변경
ALTER TABLE KH_MEMBER RENAME TO KH_MEM;
RENAME KH_MEM TO KH_MEMBER;

/*
    DROP(객체 삭제)
*/
--생성한 모든 테이블 삭제
DROP TABLE CONST_NAME;
DROP TABLE CONST_NAME2;
DROP TABLE KH_MEMBER;
DROP TABLE MEMBER;
DROP TABLE USER_CHECK;
DROP TABLE FOREIGNKEY1;
DROP TABLE FOREIGNKEY2;
DROP TABLE FOREIGNKEY3;
DROP TABLE FOREIGNKEY4;
DROP TABLE USER_GRADE;
DROP TABLE USER_GRADE2;
DROP TABLE USER_GRADE3;
DROP TABLE USER_NOTNULL;
DROP TABLE USER_PRIMARYKEY1;
DROP TABLE USER_PRIMARYKEY2;
DROP TABLE USER_PRIMARYKEY3;
DROP TABLE USER_UNIQUE1;
DROP TABLE USER_UNIQUE2;
DROP TABLE USER_UNIQUE3;